# .github/workflows/demo.yml
name: Hello PyTorch CI
on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install torch torchvision matplotlib
      - run: python hello_pytorch.py
